/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication3;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.StringReader;
import java.util.logging.Level;
import java.util.logging.Logger;


import javax.xml.parsers.DocumentBuilder;
import javax.xml.parsers.DocumentBuilderFactory;
import javax.xml.parsers.ParserConfigurationException;

import org.w3c.dom.CharacterData;
import org.w3c.dom.Document;
import org.w3c.dom.Element;
import org.w3c.dom.Node;
import org.w3c.dom.NodeList;
import org.xml.sax.InputSource;

import org.xml.sax.SAXException;

import java.io.StringWriter;
import javax.xml.transform.OutputKeys;
import javax.xml.transform.Transformer;
import javax.xml.transform.TransformerException;
import javax.xml.transform.TransformerFactory;
import javax.xml.transform.dom.DOMSource;
import javax.xml.transform.stream.StreamResult;

import org.apache.http.HttpResponse;
import org.apache.http.client.ClientProtocolException;
import org.apache.http.client.methods.HttpGet;
import org.apache.http.client.methods.HttpPost;
import org.apache.http.entity.StringEntity;
import org.apache.http.impl.client.DefaultHttpClient;


/**
 *
 * @author ivan.saldivar
 */
public class NewApplication extends javax.swing.JFrame {

    /**
     * Creates new form NewApplication
     */
    public NewApplication() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(jTextPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(0, 307, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 332, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            // TODO add your handling code here:
            fx();
        } catch (SAXException ex) {
            Logger.getLogger(NewApplication.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(NewApplication.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParserConfigurationException ex) {
            Logger.getLogger(NewApplication.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewApplication().setVisible(true);
            }
        });
    }

    public void fx() throws SAXException, IOException, ParserConfigurationException{
        String xmlRecords = "<?xml version=\"1.0\" encoding=\"utf-8\"?>"+
                            "<data>"+
                            "<employee><name>A</name><title>Manager</title></employee>"+
                            "<employee><name>B</name><title>the Boss</title></employee>"+
                            "</data>";

        String xmlRecords2 = "<?xml version=\"1.0\" encoding=\"utf-8\"?>"+
                             "<FICHA_RESIDENCIAL><ESTATUS><CODIGO>4</CODIGO>"+
                             "<GLOSA>VALOR DE PARÁMETRO NO ESTÁ DENTRO DEL DOMINIO DE VALORES PERMITIDOS (ENTEROS).</GLOSA>"+
                             "</ESTATUS>"+
                             "</FICHA_RESIDENCIAL>";

        String xmlRecords3 = "";
        
        //AQUÍ VAMOS A PROBAR EL CONSUMO DE UN SERVICIO WEB DE LA BIBLIOTECA DEL CONGRESO DE CHILE
        //MÁS REFERENCIAS PARA PROBAR OTRAS OPCIONES EN: https://www.leychile.cl/Consulta/legislacion_abierta_web_service
        DefaultHttpClient httpClient = new DefaultHttpClient();
        HttpGet getRequest = new HttpGet("https://www.leychile.cl/Consulta/obtxml?opt=7;idNorma=206396");
                        
 
        //getRequest.addHeader("accept", "application/xml");
        //getRequest.addHeader("Content-Type","text/xml; charset=utf-8");
        getRequest.setHeader("Content-Type", "text/xml; charset=utf-8");

        HttpResponse response = httpClient.execute(getRequest);

        if (response.getStatusLine().getStatusCode() != 200) {
                throw new RuntimeException("Failed : HTTP error code : "
                                + response.getStatusLine().getStatusCode());
        }

        BufferedReader br = new BufferedReader(new InputStreamReader(
                        (response.getEntity().getContent())));

        String output;
        System.out.println("Output from Server .... \n");
        while ((output = br.readLine()) != null) {
                xmlRecords3 = xmlRecords3 + output.trim();
        }
        xmlRecords3.replaceAll("\n|\r","");
        //System.out.println(xmlRecords3);
                        
        DocumentBuilder db = DocumentBuilderFactory.newInstance().newDocumentBuilder();
        InputSource is = new InputSource();

        Document doc;
        NodeList nodes, nodes2;
        String acumulado="", codigo="", glosa="", materias2="";
        

        is.setCharacterStream(new StringReader(xmlRecords3));

        doc = db.parse(is);
        //System.out.println(doc.getXmlEncoding());
        System.out.println( convertDocumentToString(doc) );
        
        ////////////////////////////////////////////////
        /*
        //cuando usamos el xmlRecords1
        is.setCharacterStream(new StringReader(xmlRecords));

        Document doc = db.parse(is);
        NodeList nodes = doc.getElementsByTagName("employee");

        for (int i = 0; i < nodes.getLength(); i++) {
          Element element = (Element) nodes.item(i);

          NodeList name = element.getElementsByTagName("name");
          Element line = (Element) name.item(0);
          System.out.println("Name: " + getCharacterDataFromElement(line));

          NodeList title = element.getElementsByTagName("title");
          line = (Element) title.item(0);
          System.out.println("Title: " + getCharacterDataFromElement(line));
        }        
        */
        
        ////////////////////////////////////////////////
        /*
        //cuando usamos el xmlRecords2
        nodes = doc.getElementsByTagName("ESTATUS");

        for (int i = 0; i < nodes.getLength(); i++) {
          Element element = (Element) nodes.item(i);

          NodeList name = element.getElementsByTagName("CODIGO");
          Element line = (Element) name.item(0);
          codigo = "CODIGO: " + getCharacterDataFromElement(line);
          System.out.println(codigo);
          
          name = element.getElementsByTagName("GLOSA");
          line = (Element) name.item(0);
          glosa="GLOSA: " + getCharacterDataFromElement(line);
          System.out.println(glosa);
          
          acumulado = this.jTextArea1.getText();
          this.jTextArea1.setText(acumulado + "CODIGO: " + codigo + "\nGLOSA: " + glosa + "\n" + convertDocumentToString(doc));
          
        } 
        */
        Element line = null;
        //cuando usamos el xmlRecords3
        String tituloNorma="", materias="", identificacionFuente="", numeroFuente=""; 
        
        nodes = doc.getElementsByTagName("Metadatos");

        if(nodes.getLength() > 0){
        //for (int i = 0; i < nodes.getLength(); i++) {
            Element element = (Element) nodes.item(0);

            NodeList name = element.getElementsByTagName("TituloNorma");
            line = (Element) name.item(0);
            if(line != null){
                tituloNorma = "TituloNorma: " + getCharacterDataFromElement(line);
            }
            System.out.println(tituloNorma);

            name = element.getElementsByTagName("IdentificacionFuente");
            line = (Element) name.item(0);
            if(line != null){
                identificacionFuente = "\nIdentificacionFuente: " + getCharacterDataFromElement(line);
            }
            System.out.println(identificacionFuente);
            
            name = element.getElementsByTagName("NumeroFuente");
            line = (Element) name.item(0);
            if(line != null){
                numeroFuente = "\nNumeroFuente: " + getCharacterDataFromElement(line);
            }
            System.out.println(identificacionFuente);            
        }

        nodes2 = doc.getElementsByTagName("Materia");

        for (int j = 0; j < nodes2.getLength(); j++) {
          Element element2 = (Element) nodes2.item(j);

          String data = element2.getFirstChild().getNodeValue();
          if(data != null ){
              materias2 = materias2 + "\n- materia= " + data;
          }
        }
            
        acumulado = this.jTextPane1.getText();
        this.jTextPane1.setText(tituloNorma + materias2 + identificacionFuente + numeroFuente+ "\n\nDOC XML FULL= \n" + convertDocumentToString(doc));
        
    } 
    
    
  public static String getCharacterDataFromElement(Element e) {
    Node child = e.getFirstChild();
    if (child instanceof CharacterData) {
      CharacterData cd = (CharacterData) child;
      return cd.getData();
    }
    return "";
  }
 
      private static String convertDocumentToString(Document doc) {
        TransformerFactory tf = TransformerFactory.newInstance();
        Transformer transformer;
        try {
            transformer = tf.newTransformer();
            // below code to remove XML declaration
            // transformer.setOutputProperty(OutputKeys.OMIT_XML_DECLARATION, "yes");
            StringWriter writer = new StringWriter();
            transformer.transform(new DOMSource(doc), new StreamResult(writer));
            String output = writer.getBuffer().toString();
            return output;
        } catch (TransformerException e) {
            e.printStackTrace();
        }
        
        return null;
    }
     private static Document convertStringToDocument(String xmlStr) {
        DocumentBuilderFactory factory = DocumentBuilderFactory.newInstance();  
        DocumentBuilder builder;  
        try  
        {  
            builder = factory.newDocumentBuilder();  
            Document doc = builder.parse( new InputSource( new StringReader( xmlStr ) ) ); 
            return doc;
        } catch (Exception e) {  
            e.printStackTrace();  
        } 
        return null;
    }
     
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables

}
